### ISSUE TITLE
Update openjdk-test and TSC docs once this repo is populated

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/TKG#1]
Centralize test doc it is currently laid out across the various test locations, the 'best' overall view currently resides in the openjdk-tests/README.md file, but we should have a ToC and a description of why test material lives across locations, and how to find info in an efficient way.

**Comment by karianna** [comment]
I've updated the TSC repo

**Comment by smlambert** [comment]
Will close this now... as the remainder of test doc updates will be completed in openjdk-tests repo under: https://github.com/AdoptOpenJDK/openjdk-tests/issues/1558
