### ISSUE TITLE
Add support for JDK_VENDOR in playlists 

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/TKG#115]
There may be several use cases where we want to differentiate by JDK_VENDOR (which is over and beyond differentiating by JDK_IMPL).  

We have currently blended the meaning of JDK_IMPL with vendor (hotspot, sap, corretto, dragonwell are all hotspot VM impl based, but rightly we should categorize them as JDK_VENDOR (adopt, sap, amazon, alibaba) or whatever value is returned by a query of java.vendor.  (related: https://github.com/AdoptOpenJDK/openjdk-build/issues/465)

As there are tests that may be vendor specific (many build/packaging tests for example).

**Comment by adamfarley** [comment]
Looking into this, so we can create the adopt-only test needed for https://github.com/AdoptOpenJDK/openjdk-build/pull/2226

**Comment by smlambert** [comment]
This may end up to be a documentation effort, as JDK_IMPL is currently nearly equivalent to JDK_VENDOR and we may not have a need for an explicit VM_IMPL differentiator. 

Will discuss with @renfeiw and @llxia this week.

**Comment by smlambert** [comment]
Some discussion on the topic:
We currently populate JDK_IMPL with value returned from [java.vm.name](https://github.com/AdoptOpenJDK/TKG/blob/da88ca45cf9a45726f9dbe94778ec1efcd947ecd/src/org/openj9/envInfo/JavaInfo.java#L104).   We will look at what is returned by a query to java.vm.vendor (from each of the known/accessible OpenJDK distributors) and possibly use a combination of java.vm.name and java.vm.vendor.

**Comment by smlambert** [comment]
Table of Vendors and Expected System.properties values

|Impl|Vendor| java.vendor=xxxx|
| --- | --- | --- |
| Hotspot | AdoptOpenJDK Hotspot link |  AdoptOpenJDK |
| " | Upstream/OpenJDK/RH | Oracle Corporation  |
| " | Alibaba Dragonwell | Alibaba  |
| " | Amazon Corretto | Amazon.com Inc.  |
| " | SAP Sapmachine | SAP SE  |
| " | Azul Zulu |  Azul Systems, Inc. |
| " | Bellsoft Liberica | BellSoft  |
| OpenJ9 | AdoptOpenJDK OpenJ9 |  AdoptOpenJDK |
| " | IBM |  IBM  |

As verified through: [Grinder_TKG 89](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_TKG/89) - [Grinder_TKG 96](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_TKG/96)

**Comment by renfeiw** [comment]
> Table of Vendors and Expected System.properties values
> 
> Impl	Vendor	java.vendor=xxxx
> Hotspot	AdoptOpenJDK Hotspot	AdoptOpenJDK
> "	Upstream/OpenJDK/RH	Oracle Corporation
> "	Alibaba Dragonwell	Alibaba
> "	Amazon Corretto	Amazon.com Inc.
> "	SAP Sapmachine	SAP SE
> "	Azul Zulu	Azul Systems, Inc.
> "	Bellsoft Liberica	BellSoft
> OpenJ9	AdoptOpenJDK OpenJ9	AdoptOpenJDK
> "	IBM	IBM
> As verified through: [Grinder_TKG 89](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_TKG/89) - [Grinder_TKG 96](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_TKG/96)

I am working on a PR to add JDK_VENDOR. This information is really helpful!

**Comment by smlambert** [comment]
@renfeiw - take a look at smlambert:vendor branch, where I started... but still didn't add the playlist element and ability to add filtering.

**Comment by smlambert** [comment]
Fixed by https://github.com/AdoptOpenJDK/TKG/pull/142 - thanks @renfeiw !
