### ISSUE TITLE
Test jobs produce FAILURE when no tests are run as Playlist does not contain the given target

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/TKG#138]
Some sanity.external sub test jobs do not contain any targets matching the "external" target, eg:netty and spring:
https://ci.adoptopenjdk.net/view/Failing%20Test%20Jobs/job/Test_openjdk11_hs_sanity.external_x86-64_linux_netty/
https://ci.adoptopenjdk.net/view/Failing%20Test%20Jobs/job/Test_openjdk11_hs_sanity.external_s390x_linux_spring/1/console
```
22:25:12  TAP Reports Processing: START
22:25:12  Looking for TAP results report in workspace using pattern: **/*.tap
22:25:12  Did not find any matching files. Setting build result to FAILURE.
```

**Comment by andrew-m-leonard** [comment]
Seems this behaviour is actually "desired".
I will create a separate PR to add MachineInfo to the netty and spring Playlists to resolve the immediate issue.

**Comment by karianna** [comment]
@andrew-m-leonard - can this be closed now?
