### ISSUE TITLE
Auto-detect does not work for arm 32 builds

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/TKG#18]
See https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1267, think auto-detect does not work as the value of java.vm.name is unexpected.

01:47:02  AUTO_DETECT is set to true
01:47:02  /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java -cp ./bin/TestKitGen.jar org.openj9.envInfo.EnvDetector JavaInfo
01:47:02  System.getProperty('os.name')=Linux
01:47:02  
01:47:02  System.getProperty('os.arch')=arm
01:47:02  
01:47:02  System.getProperty('java.fullversion')=null
01:47:02  
01:47:02  Cannot determine System.getProperty('os.arch')=arm
01:47:02  
01:47:02  System.getProperty('java.vm.name')=OpenJDK Zero VM
01:47:02  
01:47:02  run_configure.mk:29: recipe for target 'testconfig' failed
01:47:02  make: *** [testconfig] Error 1

**Comment by aahlenst** [comment]
@smlambert Is there a workaround? I just stumbled on this one.

**Comment by smlambert** [comment]
Yes, you can disable AUTO_DETECT and explicitly set SPEC / JDK_IMPL / JDK_VERSION to work-around until this is fixed.  

So, if running locally:
export AUTO_DETECT=false
export SPEC= linux_arm
export JDK_IMPL=hotspot
export JDK_VERSION=8 // (or as appropriate)

<hr/>

or in Grinder, unset AUTO_DETECT and make sure to fill in PLATFORM/JDK_IMPL/JDK_VERSION explicitly 

<img width="525" alt="Screen Shot 2020-06-28 at 10 17 36 AM" src="https://user-images.githubusercontent.com/2836948/85950094-a7025600-b928-11ea-9f90-f6e8f4b275ab.png">

Also think it may be a relatively simple fix (https://github.com/AdoptOpenJDK/TKG/pull/88) but do not have a machine on which to verify it.
