### ISSUE TITLE
Test of Grinder_Simple does not work

### ISSUE THREAD

**Issue by KKES335** [AdoptOpenJDK/TKG#32]
Please see the following results.
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Simple/2124/console
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Simple/2123/console

I can see the message "autoGen.mk:16: C:/Users/jenkins/workspace/Grinder_Simple/openjdk-tests/\\TKG\\dependencies.mk: No such file or directory".

**Comment by toshiona** [comment]
(I'm co-worker of KKES335.)
We wonder why makeGen.mk related log wasn't recorded after "./openjdk-tests/maketest.sh ./openjdk-tests _special.functional".

**Comment by smlambert** [comment]
The [Grinder](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/) job was updated so you can always use that (it calls the same script as Grinder_Simple, but shows more of the parameters that can be passed in).

We did not update Grinder_Simple after various changes as we should have done.  I created a new Grinder_Simple job that is working and renamed the old one to Grinder_SImple_Old (to keep its history for a while, then I will delete it).  I have also deleted Grinder_Advanced_Deprecated job.

I tried to relaunch your jobs but @KKES335 will need to update branch 1479 as it is missing some important updates, in particular, https://github.com/AdoptOpenJDK/openjdk-tests/pull/1521

I've launched BUILD_LIST=functional/MBCS_Tests, TARGET=sanity.functional from master in this job, to ensure it works: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Simple/3

**Comment by KKES335** [comment]
@smlambert  Thank you for your support.
I updated my repository and then executed a grinder job.
Test of the grinder job worked. https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Simple/4/
