### ISSUE TITLE
Update rerun link based on Jenkins server

### ISSUE THREAD

**Issue by llxia** [AdoptOpenJDK/TKG#44]
At the end of the run, TKG provides rerun link (below).
```
16:40:35  To rebuild the failed test in a jenkins job, copy the following link and fill out the <Jenkins URL> and <FAILED test target>:
16:40:35  <Jenkins URL>/parambuild/?JDK_VERSION=11&JDK_IMPL=openj9&BUILD_LIST=openjdk&PLATFORM=ppc64_aix&TARGET=<FAILED test target>
16:40:35  
16:40:35  For example, to rebuild the failed tests in <Jenkins URL>=https://ci.adoptopenjdk.net/job/Grinder, use the following links:
16:40:35  https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=11&JDK_IMPL=openj9&BUILD_LIST=openjdk&PLATFORM=ppc64_aix&TARGET=jdk_io_0
```

We need to update rerun link based on Jenkins server. We can use [HUDSON_URL](https://github.com/AdoptOpenJDK/openjdk-tests/blob/e459da26fb67070ad0e326af40a38e20d29439db/buildenv/jenkins/JenkinsfileBase#L640) for Jenkins server. The default value should still be `https://ci.adoptopenjdk.net/`.

**Comment by smlambert** [comment]
Related to updating rerun link: https://github.com/AdoptOpenJDK/openjdk-tests/issues/1550

**Comment by llxia** [comment]
PR https://github.com/AdoptOpenJDK/TKG/pull/46

**Comment by llxia** [comment]
Close this issue as the PR is merged.
