### ISSUE TITLE
Not able to set `--iterations` when running the tests locally

### ISSUE THREAD

**Issue by VermaSh** [AdoptOpenJDK/TKG#59]
TestKitGen has a iterations argument `--iterations` on line 39 in makeGen.mk[1] Is there a way to set that for local tests?
I have tried exporting `TEST_ITERATIONS` before make compile but didn’t have any luck. From the looks it the variable being substituted on line 39 in makeGen.mk[1] `--iterations=$(TEST_ITERATIONS)` doesn’t look like an environment variable substitution. I am also not too familiar with make files so I could be wrong

If it is not supported I could try adding it as being able to run a grinder locally would be handy for intermittent bugs

[1] https://github.com/AdoptOpenJDK/TKG/blob/master/makeGen.mk#L39

**Comment by renfeiw** [comment]
We use the `TEST_ITERATIONS` as a parameter when invoking make target, for example `make _sanity TEST_ITERATIONS=2`. I will make an update to TKG to make `export TEST_ITERATIONS=2` work as well.

**Comment by VermaSh** [comment]
@renfeiw ah didn't know that. Thank you for that information.

Could we also document the usage in a guide? would be really helpful for new users

**Comment by renfeiw** [comment]
Sure, I can update the doc when the PR for environment variable is merged.
