### ISSUE TITLE
Remove platform specific code in getDependencies script

### ISSUE THREAD

**Issue by renfeiw** [AdoptOpenJDK/TKG#68]
We are using `curl` on zos and `wget` on the other platforms. These two pieces of code can be merged so we use `curl` across all platforms.

**Comment by llxia** [comment]
@NikolaMilijevic1

**Comment by llxia** [comment]
https://github.com/AdoptOpenJDK/TKG/blob/3205e0d0c8631ba96d1cafa360e703ed23e972c0/scripts/getDependencies.pl#L234

**Comment by renfeiw** [comment]
@nikolamilijevic1 The Jenkins builds are using pre-staged jars from test.getDependency build, so getDependencies script will not be invoked in the grinder run. To test your change, you need to disable the pre-stage step and execute the getDependencies script. You can temporarily comment out the try catch statements (https://github.com/AdoptOpenJDK/openjdk-tests/blob/fb7463af44f406b233def68085a7bfc5f4bb7e83/buildenv/jenkins/JenkinsfileBase#L446) and use your temporary AdoptOpenJDK branch in grinder.
