### ISSUE TITLE
Create a generic name for asm jar

### ISSUE THREAD

**Issue by llxia** [AdoptOpenJDK/TKG#90]
We use asm.jar name contains the specific version. 
https://github.com/AdoptOpenJDK/TKG/blob/70d471246847943ac59a8840998c6e625f181056/scripts/getDependencies.pl#L66

The problem is that every time we upgrade the jar, we need to update all the files that use it. (See https://github.com/eclipse/openj9/pull/10057/files)
To avoid this, we should have a generic name (similar to testing, commander, etc). We can just call it `asm.jar`

**Comment by theresa-m** [comment]
good idea @llxia :D
