### ISSUE TITLE
SHA mismatch for asm-8.0.1.jar

### ISSUE THREAD

**Issue by pshipton** [AdoptOpenJDK/TKG#92]
Cloned TKG and ran a `make compile`, getting the following error.
```
--------------------------------------------
Starting download third party dependent jars
--------------------------------------------
downloading dependent third party jars to /home/peter/test/openjdk-tests/TKG/../TKG/lib
downloading https://repo1.maven.org/maven2/org/ow2/asm/asm-all/6.0_BETA/asm-all-6.0_BETA.jar
--> file downloaded to /home/peter/test/openjdk-tests/TKG/../TKG/lib/asm-all.jar
downloading https://repository.ow2.org/nexus/content/repositories/releases/org/ow2/asm/asm/8.0.1/asm-8.0.1.jar
--> file downloaded to /home/peter/test/openjdk-tests/TKG/../TKG/lib/asm-8.0.1.jar
Expected sha is: 3f5199523fb95304b44563f5d56d9f5a07270669,
Actual sha is  : a236c777042003fc6fe13c53825e06494d7185fb.
ERROR: sha checksum error.
Please delete /home/peter/test/openjdk-tests/TKG/../TKG/lib/asm-8.0.1.jar and rerun the program!makefile:40: recipe for target 'getdependency' failed
make: *** [getdependency] Error 255
```

**Comment by pshipton** [comment]
@llxia @smlambert fyi

**Comment by llxia** [comment]
The [asm-8.0.1.jar.sha1](https://repository.ow2.org/nexus/content/repositories/releases/org/ow2/asm/asm/8.0.1/asm-8.0.1.jar.sha1) on the downloading web site is `3f5199523fb95304b44563f5d56d9f5a07270669`. 

Nightly builds seem fine. Also, I cannot reproduce the above error on my local. The above error is on which platform?

**Comment by pshipton** [comment]
I'm running on xlinux, RHEL 7.7

**Comment by pshipton** [comment]
I deleted lib/asm-8.0.1.jar file and re-ran `make compile` and it worked.

**Comment by pshipton** [comment]
Before I deleted the file.
`sha256sum asm-8.0.1.jar`
`3cb35c76707a90a9bd8f96895256f0041646bceb5247e269e46cb2dff9c732d4  asm-8.0.1.jar`

**Comment by pshipton** [comment]
Guess I should have used `sha1sum`
